import { test, expect, type Page } from '@playwright/test'
import { createResume } from '../utils/flows'

async function createPopulatedEditor(page: Page, template?: string) {
  await createResume(page, template)
  for (const label of ['Personal details', 'Summary', 'Work experience', 'Education']) {
    await expect(page.getByRole('heading', { name: label, exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Fill with example', exact: true }).click()
    await page.getByRole('button', { name: 'Next', exact: true }).click()
  }
  await page.getByRole('button', { name: 'Full Editor', exact: true }).click()
  await expect(page).toHaveURL(/\/editor\/[^/]+$/)
}

test('canvas selects exact fields, keeps the page still, and offers a clean preview', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await createPopulatedEditor(page)
  const canvas = page.getByLabel('Resume canvas', { exact: true })
  const panel = page.getByLabel('Properties panel')
  const company = canvas.getByRole('button', { name: 'Edit company', exact: true }).nth(1)
  await company.scrollIntoViewIfNeeded()
  const scroll = await canvas.evaluate(el => el.scrollTop)
  await company.click()
  await expect(panel.getByRole('textbox', { name: 'Company', exact: true }).nth(1)).toBeFocused()
  expect(await canvas.evaluate(el => el.scrollTop)).toBeCloseTo(scroll, 0)
  await expect(canvas.locator('[data-canvas-selected]')).toHaveCount(1)
  await panel.getByRole('textbox', { name: 'Company', exact: true }).nth(1).fill('Canvas Example Labs')
  await panel.getByRole('textbox', { name: 'Company', exact: true }).nth(1).blur()
  await expect(company).toHaveText('Canvas Example Labs')

  const toolbar = page.getByRole('toolbar', { name: 'Canvas editing controls' })
  await expect(toolbar.getByRole('button')).toHaveCount(1)
  await expect(page.getByRole('note', { name: 'Canvas editing tip' })).toBeVisible()
  const toolbarBox = (await toolbar.boundingBox())!
  const labelBox = (await toolbar.getByText('Company', { exact: true }).boundingBox())!
  expect(labelBox.x).toBeGreaterThan(toolbarBox.x + toolbarBox.width / 2)
  await panel.getByRole('tab', { name: 'Design', exact: true }).click()
  await expect(page.getByRole('tab', { name: 'Design', exact: true })).toHaveAttribute('aria-selected', 'true')
  await company.click()
  await expect(page.getByRole('tab', { name: 'Design', exact: true })).toHaveAttribute('aria-selected', 'true')
  await panel.getByRole('tab', { name: 'Content', exact: true }).click()
  await expect(panel.getByRole('textbox', { name: 'Company', exact: true }).nth(1)).toBeFocused()

  await canvas.getByRole('button', { name: 'Edit description item', exact: true }).nth(1).click()
  await expect(panel.getByRole('textbox', { name: 'Achievements / bullet points item 2' }).first()).toBeFocused()
  await page.mouse.move(0, 0)
  await page.screenshot({ path: testInfo.outputPath('canvas-inspector.png') })

  const preview = page.getByRole('button', { name: 'Clean preview', exact: true })
  await preview.click()
  await expect(preview).toHaveAttribute('aria-pressed', 'true')
  await expect(canvas.locator('[data-canvas-selected]')).toHaveCount(0)
  await expect(canvas.getByRole('button')).toHaveCount(0)
  await expect(page.locator('[data-canvas-element-label]')).toHaveCount(0)
  await expect(canvas.getByText('Canvas Example Labs', { exact: true })).toBeVisible()
  await preview.click()
  await expect(canvas.locator('[data-canvas-selected]')).toHaveCount(1)

  await company.dblclick()
  const inline = canvas.locator('[contenteditable="true"]')
  await expect(inline).toBeFocused()
  await inline.fill('Inline Example Labs')
  await inline.press('Enter')
  await expect(company).toHaveText('Inline Example Labs')
  await expect(panel.getByRole('textbox', { name: 'Company', exact: true }).nth(1)).toHaveValue('Inline Example Labs')
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  await page.reload()
  await expect(canvas.getByRole('button', { name: 'Edit company', exact: true }).nth(1)).toHaveText('Inline Example Labs')
})

test('mobile canvas opens the clicked entry in Content and supports a quiet preview', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await createPopulatedEditor(page)
  const views = page.getByRole('navigation', { name: 'Editor views' })
  await views.getByRole('button', { name: 'Preview', exact: true }).click()
  const canvas = page.getByLabel('Resume canvas', { exact: true })
  await canvas.getByRole('button', { name: 'Edit company', exact: true }).nth(1).click()
  await expect(views.getByRole('button', { name: 'Content', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const company = page.getByLabel('Properties panel').getByRole('textbox', { name: 'Company', exact: true }).nth(1)
  await expect(company).toBeFocused()
  await expect(company).toBeInViewport()
  await views.getByRole('button', { name: 'Preview', exact: true }).click()
  await page.getByRole('button', { name: 'Clean preview', exact: true }).click()
  await expect(canvas.getByRole('button')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('canvas divider controls change the line, persist, and reset without shifting content', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await createPopulatedEditor(page, 'Clarity')
  const canvas = page.getByLabel('Resume canvas', { exact: true })
  const panel = page.getByLabel('Properties panel')
  const line = canvas.locator('[data-canvas-decoration="divider"]').first()
  const hitTarget = line.getByRole('button', { name: 'Edit divider line' })
  const original = await line.boundingBox()
  const summary = canvas.getByRole('button', { name: 'Edit summary', exact: true })
  await summary.click()
  const summaryY = (await summary.boundingBox())!.y
  expect((await hitTarget.boundingBox())!.height).toBeGreaterThanOrEqual(13.9)
  // Click beyond the painted stroke, inside its more forgiving hit area.
  await hitTarget.click({ position: { x: 30, y: 2 } })
  await expect(page.getByRole('tab', { name: 'Design', exact: true })).toHaveAttribute('aria-selected', 'true')
  const thickness = panel.getByRole('spinbutton', { name: 'Thickness (pt)' })
  const length = panel.getByRole('spinbutton', { name: 'Length (%)' })
  await expect(thickness).toBeVisible()
  await thickness.fill('3')
  await thickness.press('Enter')
  await length.fill('60')
  await length.press('Enter')
  await panel.getByRole('button', { name: 'Centre line', exact: true }).click()
  await panel.getByLabel('Line colour', { exact: true }).click()
  await page.locator('.ant-color-picker-hex-input input').fill('208475')
  await page.locator('.ant-color-picker-hex-input input').press('Enter')
  await panel.getByLabel('Line colour', { exact: true }).click()
  await expect(line.locator('[aria-hidden="true"]').last()).toHaveCSS('background-color', 'rgb(32, 132, 117)')
  const changed = await line.boundingBox()
  expect(changed!.width).toBeCloseTo(original!.width * 0.6, 0)
  expect(changed!.x).toBeCloseTo(original!.x + original!.width * 0.2, 0)
  expect(changed!.height).toBeGreaterThan(original!.height)
  expect((await summary.boundingBox())!.y).toBeCloseTo(summaryY, 0)
  await page.mouse.move(0, 0)
  await page.screenshot({ path: testInfo.outputPath('divider-controls.png') })
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  await page.reload()
  await hitTarget.click()
  await expect(thickness).toHaveValue('3')
  await expect(length).toHaveValue('60')
  await expect(line.locator('[aria-hidden="true"]').last()).toHaveCSS('background-color', 'rgb(32, 132, 117)')
  await panel.getByRole('button', { name: 'Reset styling', exact: true }).click()
  await expect(length).toHaveValue('100')
  const restored = await line.boundingBox()
  expect(restored!.width).toBeCloseTo(original!.width, 0)
  expect(restored!.height).toBeCloseTo(original!.height, 0)
  // Section rules use the same controls, even when Content was selected.
  await page.getByRole('tab', { name: 'Content', exact: true }).click()
  await canvas.getByRole('button', { name: 'Edit divider line' }).nth(2).click()
  await expect(thickness).toBeVisible()
  await expect(canvas.locator('[data-canvas-selected]')).toHaveCount(1)
  const selectedLine = canvas.locator('[data-canvas-decoration="divider"][data-canvas-selected]')
  await expect(selectedLine).toHaveCSS('outline-offset', '0px')
  await expect(selectedLine).toHaveCSS('border-radius', '0px')
  await page.mouse.move(0, 0)
  const label = page.locator('[data-canvas-element-label]')
  await expect(label).toBeVisible()
  await expect(label).toHaveText('Divider line')
  const heading = await canvas.getByRole('button', { name: 'Edit experience section title', exact: true }).evaluate((element) => {
    const range = document.createRange()
    range.selectNodeContents(element)
    return range.getBoundingClientRect().toJSON()
  })
  const badge = (await label.boundingBox())!
  expect(badge.x >= heading.right || badge.x + badge.width <= heading.left
    || badge.y >= heading.bottom || badge.y + badge.height <= heading.top).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('divider-selection.png') })
  await canvas.getByRole('button', { name: 'Edit fullName', exact: true }).hover()
  await expect(label).toHaveText('Full name')
  await expect(label).toBeVisible()
  await canvas.getByRole('button', { name: 'Open profile photo in Personal Info', exact: true }).hover()
  await expect(label).toHaveText('Photo')
  await expect(label).toBeVisible()
  await page.mouse.move(0, 0)
  await expect(label).toHaveText('Divider line')
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect(label).toBeVisible()
  const area = (await canvas.boundingBox())!
  const zoomedBadge = (await label.boundingBox())!
  expect(zoomedBadge.x).toBeGreaterThanOrEqual(area.x)
  expect(zoomedBadge.x + zoomedBadge.width).toBeLessThanOrEqual(area.x + area.width)
})

test('mobile divider selection opens its Design controls directly', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await createPopulatedEditor(page, 'Clarity')
  const views = page.getByRole('navigation', { name: 'Editor views' })
  await views.getByRole('button', { name: 'Preview', exact: true }).click()
  const line = page.getByLabel('Resume canvas', { exact: true }).getByRole('button', { name: 'Edit divider line' }).first()
  expect((await line.boundingBox())!.height).toBeGreaterThanOrEqual(13.9)
  await line.click()
  await expect(views.getByRole('button', { name: 'Design', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const thickness = page.getByLabel('Properties panel').getByRole('spinbutton', { name: 'Thickness (pt)' })
  await expect(thickness).toBeInViewport()
  await thickness.fill('2')
  await thickness.press('Enter')
  await views.getByRole('button', { name: 'Preview', exact: true }).click()
  await line.click()
  await expect(thickness).toHaveValue('2')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('canvas labels include background panels without hiding their content', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await createPopulatedEditor(page, 'Foundation')
  const canvas = page.getByLabel('Resume canvas', { exact: true })
  await canvas.getByRole('button', { name: 'Edit shape / panel', exact: true }).first().click({ position: { x: 8, y: 8 } })
  await page.mouse.move(0, 0)
  const label = page.locator('[data-canvas-element-label]')
  await expect(label).toHaveText('Shape / panel')
  await expect(label).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('panel-label.png') })
  await canvas.getByRole('button', { name: 'Edit fullName', exact: true }).click()
  await expect(label).toHaveText('Full name')
  await expect(label).toBeVisible()
})

test('contact labels stay beside their fields on a wide canvas', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1920, height: 1000 })
  await createPopulatedEditor(page, 'Clarity')
  const canvas = page.getByLabel('Resume canvas', { exact: true })
  await canvas.getByRole('button', { name: 'Edit website', exact: true }).click()
  const phone = canvas.getByRole('button', { name: 'Edit phone', exact: true })
  await phone.hover()
  const label = page.locator('[data-canvas-element-label]')
  await expect(label).toHaveText('Phone')
  await expect(label).toBeVisible()
  // Hover labels describe the pointer target; toolbar actions still describe
  // the selected field they will actually edit.
  await expect(page.getByRole('toolbar', { name: 'Canvas editing controls' }).getByText('Website', { exact: true })).toBeVisible()
  const field = (await phone.boundingBox())!
  const badge = (await label.boundingBox())!
  const dx = Math.max(field.x - badge.x - badge.width, badge.x - field.x - field.width, 0)
  const dy = Math.max(field.y - badge.y - badge.height, badge.y - field.y - field.height, 0)
  expect(Math.hypot(dx, dy)).toBeLessThanOrEqual(12)
  expect(badge.x + badge.width).toBeGreaterThan(field.x)
  expect(badge.x).toBeLessThan(field.x + field.width)
  await expect(canvas.locator('[title]')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('phone-label.png') })
})
