import { test, expect } from '@playwright/test'
import { createResume } from '../utils/flows'

test('guided setup requires every section and prevents jumping past incomplete steps', async ({ page }) => {
  await createResume(page)
  const next = page.getByRole('button', { name: 'Next', exact: true })
  const steps = page.getByLabel('Guided setup steps')
  await expect(page.getByRole('button', { name: 'Skip for now' })).toHaveCount(0)

  await next.click()
  await expect(page.getByRole('textbox', { name: 'Full name' })).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByRole('textbox', { name: 'Email', exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByRole('textbox', { name: 'Full name' }).fill('Jordan Rivera')
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('jordan@example.com')

  // A later step redirects to the first incomplete prerequisite.
  await steps.getByRole('button', { name: /Skills/ }).click()
  await expect(page.getByRole('heading', { name: 'Summary', exact: true })).toBeVisible()
  const summary = page.getByRole('textbox', { name: 'Summary', exact: true })
  await expect(summary).toHaveAttribute('required', '')
  await expect(summary).toHaveAttribute('aria-invalid', 'true')
  await summary.fill('   ')
  await next.click()
  await expect(summary).toHaveAttribute('aria-invalid', 'true')
  await summary.fill('Engineer building accessible applications and reliable services.')
  await next.click()

  await expect(page.getByRole('heading', { name: 'Work experience', exact: true })).toBeVisible()
  await next.click()
  await expect(page.getByRole('alert')).toHaveText('Add at least one work experience entry.')
  await page.getByRole('button', { name: 'Add Experience', exact: true }).click()
  await page.getByRole('textbox', { name: 'Company', exact: true }).fill('Example Labs')
  await next.click()
  await expect(page.getByRole('textbox', { name: 'Role / Job title' })).toHaveAttribute('aria-invalid', 'true')
  await page.getByRole('textbox', { name: 'Role / Job title' }).fill('Engineer')
  await next.click()

  await expect(page.getByRole('heading', { name: 'Education', exact: true })).toBeVisible()
  await next.click()
  await expect(page.getByRole('alert')).toHaveText('Add at least one education entry.')
  await page.getByRole('button', { name: 'Add Education', exact: true }).click()
  await page.getByRole('textbox', { name: 'Institution', exact: true }).fill('Example University')
  await next.click()
  await expect(page.getByRole('textbox', { name: 'Degree', exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByRole('textbox', { name: 'Degree', exact: true }).fill('BSc')
  await next.click()

  await expect(page.getByRole('heading', { name: 'Skills', exact: true })).toBeVisible()
  const finish = page.getByRole('button', { name: 'Finish', exact: true })
  await finish.click()
  await expect(page.getByRole('alert')).toHaveText('Add at least one skill category and skill.')
  await page.getByRole('button', { name: 'Add Skill Category', exact: true }).click()
  await page.getByRole('textbox', { name: 'Category name', exact: true }).fill('Languages')
  await page.getByRole('button', { name: 'Add skill', exact: true }).click()
  await finish.click()
  await expect(page.getByRole('textbox', { name: 'Skill name', exact: true })).toHaveAttribute('aria-invalid', 'true')
  await page.getByRole('textbox', { name: 'Skill name', exact: true }).fill('TypeScript')
  await finish.click()
  await expect(page).toHaveURL(/\/editor\/[^/]+$/)
})

test('Full Editor saves an incomplete work entry after Next is blocked', async ({ page }) => {
  await createResume(page)
  for (const label of ['Personal details', 'Summary']) {
    await expect(page.getByRole('heading', { name: label, exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Fill with example', exact: true }).click()
    await page.getByRole('button', { name: 'Next', exact: true }).click()
  }
  await page.getByRole('button', { name: 'Add Experience', exact: true }).click()
  await page.getByRole('textbox', { name: 'Company', exact: true }).fill('Draft Company')
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Role / Job title' })).toHaveAttribute('aria-invalid', 'true')
  await page.getByRole('button', { name: 'Full Editor', exact: true }).click()
  await expect(page).toHaveURL(/\/editor\/[^/]+$/)
  await page.reload()
  await page.getByRole('button', { name: 'Edit Experience section', exact: true }).click()
  const panel = page.getByLabel('Properties panel')
  await expect(panel.getByRole('textbox', { name: 'Company', exact: true })).toHaveValue('Draft Company')
  await expect(panel.getByRole('textbox', { name: 'Role / Job title' })).toHaveValue('')
  await expect(panel.getByRole('textbox', { name: 'Role / Job title' })).not.toHaveAttribute('required', '')
})
