import { expect, test, type Download } from '@playwright/test'
import { createResume, createResumeInFullEditor, goToFullEditor } from '../utils/flows'

async function downloadBytes(download: Download) {
  const stream = await download.createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  return Buffer.concat(chunks)
}

test('section navigation works on the first click while the current field saves', async ({ page }) => {
  await createResumeInFullEditor(page)
  await page.getByRole('textbox', { name: 'Full name', exact: true }).fill('Navigation Example')
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('navigation@example.com')
  const summaryButton = page.getByRole('button', { name: 'Edit Summary section', exact: true })
  const before = await summaryButton.boundingBox()
  // The click itself blurs and saves the email. Readiness updates must not move
  // the section button between pointerdown and pointerup, swallowing the click.
  await summaryButton.click()
  await expect(page.getByRole('textbox', { name: 'Summary', exact: true })).toBeVisible()
  expect(Math.abs((await summaryButton.boundingBox())!.y - before!.y)).toBeLessThan(2)
  await page.getByRole('textbox', { name: 'Summary', exact: true }).fill('Engineer building reliable web applications and accessible user experiences.')
  await page.getByRole('button', { name: 'Edit Experience section', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Add Experience', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit Summary section', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Summary', exact: true })).toHaveValue(/accessible user experiences/)
})

test('sharing includes the focused draft and opens an independent copy in a fresh browser', async ({ page, browser }) => {
  await createResumeInFullEditor(page)
  const originalUrl = page.url()
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('snapshot@example.com')
  await page.getByRole('textbox', { name: 'Full name', exact: true }).fill('Shared Snapshot')
  await page.getByRole('button', { name: 'Share resume', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Share resume', exact: true })
  await dialog.getByRole('radio', { name: 'Editable copy', exact: true }).check()
  await expect(dialog.getByRole('textbox', { name: 'Share link' })).toHaveValue(/\/share#/)
  const link = await dialog.getByRole('textbox', { name: 'Share link' }).inputValue()
  await dialog.getByRole('button', { name: 'Close dialog' }).click()
  const recipient = await browser.newContext()
  try {
    await recipient.addInitScript(() => localStorage.setItem('resume-studio:editor-tour:v1', 'seen'))
    const copy = await recipient.newPage()
    await copy.goto(link)
    await expect(copy).toHaveURL(/\/editor\/[^/]+$/)
    expect(copy.url()).not.toBe(originalUrl)
    await expect(copy.getByRole('textbox', { name: 'Full name', exact: true })).toHaveValue('Shared Snapshot')
    await expect(copy.getByRole('textbox', { name: 'Email', exact: true })).toHaveValue('snapshot@example.com')
    await copy.getByRole('textbox', { name: 'Full name', exact: true }).fill('Recipient Copy')
    await copy.getByRole('link', { name: 'Back to dashboard' }).click()
    await expect(copy.getByRole('article')).toHaveCount(1)
    await page.reload()
    await expect(page.getByRole('textbox', { name: 'Full name', exact: true })).toHaveValue('Shared Snapshot')
  } finally {
    await recipient.close()
  }
})

test('backup restore preserves an uploaded photo and rejects invalid files without changing existing resumes', async ({ page }) => {
  await createResume(page, 'Foundation')
  await goToFullEditor(page)
  await page.getByRole('textbox', { name: 'Full name', exact: true }).fill('Backup Example')
  await page.getByText('Profile image', { exact: true }).click()
  const photo = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 40
    canvas.height = 40
    const context = canvas.getContext('2d')!
    context.fillStyle = '#7c3aed'
    context.fillRect(0, 0, 40, 40)
    return canvas.toDataURL('image/png').split(',')[1]
  })
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: 'Upload photo', exact: true }).click()
  await (await chooser).setFiles({ name: 'profile.png', mimeType: 'image/png', buffer: Buffer.from(photo, 'base64') })
  await expect(page.getByRole('button', { name: 'Change photo', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Back to dashboard' }).click()
  await page.goto('/settings')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download backup', exact: true }).click()
  const bytes = await downloadBytes(await download)
  const backup = JSON.parse(bytes.toString())
  expect(backup.resumes).toHaveLength(1)
  expect(backup.images).toHaveLength(1)
  expect(backup.resumes[0].personalInfo.fullName).toBe('Backup Example')
  const upload = page.getByLabel('Choose a Resume Builder backup')
  await upload.setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"invalid":true}') })
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await upload.setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: bytes })
  await page.getByRole('dialog', { name: 'Restore your resumes' }).getByRole('button', { name: 'Restore copies' }).click()
  await expect(page.getByRole('status')).toContainText('1 resume restored')
  await page.goto('/app')
  await expect(page.getByRole('article')).toHaveCount(2)
  await page.getByRole('link', { name: 'Open resume: Untitled Resume (Restored)', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Full name', exact: true })).toHaveValue('Backup Example')
  await page.getByText('Profile image', { exact: true }).click()
  await expect(page.getByRole('button', { name: 'Change photo', exact: true })).toBeVisible()
})

test('mobile navigation, theme persistence and invalid-route recovery work', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/')
  for (const [label, path] of [['Templates', '/templates'], ['Settings', '/settings'], ['My Resumes', '/app'], ['Home', '/']] as const) {
    await page.getByRole('button', { name: 'Open menu' }).click()
    await page.getByRole('dialog', { name: 'Menu' }).getByRole('link', { name: label, exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`${path === '/' ? '' : path}/?$`))
    await expect(page.getByRole('dialog', { name: 'Menu' })).toBeHidden()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.goto('/settings')
  await page.getByText('Dark', { exact: true }).click()
  await page.reload()
  await expect(page.getByRole('radio', { name: 'Dark', exact: true })).toBeChecked()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.goto('/missing-page')
  await page.getByRole('link', { name: 'Go to Dashboard' }).click()
  await expect(page.getByRole('heading', { name: 'My Resumes' })).toBeVisible()
  await page.goto('/editor/missing-resume')
  await expect(page).toHaveURL(/\/app$/)
  await page.goto('/share#invalid')
  await expect(page.getByRole('heading', { name: 'We couldn’t open this link' })).toBeVisible()
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('invalid')
  await page.getByRole('link', { name: 'My resumes', exact: true }).last().click()
  await expect(page).toHaveURL(/\/app$/)
})

test('skill stars support the keyboard, persist after reload, and survive reset undo', async ({ page }) => {
  await createResumeInFullEditor(page)
  await page.getByRole('textbox', { name: 'Full name', exact: true }).fill('Skills Example')
  await page.getByRole('button', { name: 'Edit Skills section', exact: true }).click()
  await page.getByRole('button', { name: 'Add Skill Category', exact: true }).click()
  await page.getByRole('textbox', { name: 'Category name', exact: true }).fill('Engineering')
  await page.getByRole('button', { name: 'Add skill', exact: true }).click()
  await page.getByRole('textbox', { name: 'Skill name', exact: true }).fill('TypeScript')
  const stars = page.getByRole('radiogroup', { name: 'Proficiency for TypeScript' })
  await stars.getByRole('radio', { name: '3 out of 5', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(stars.getByRole('radio', { name: '4 out of 5', exact: true })).toBeChecked()
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Edit Skills section', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Category name', exact: true })).toHaveValue('Engineering')
  await expect(stars.getByRole('radio', { name: '4 out of 5', exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'Reset resume', exact: true }).click()
  const reset = page.getByRole('dialog', { name: 'Reset resume', exact: true })
  await reset.getByRole('checkbox', { name: 'Content', exact: true }).check()
  await reset.getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Full name', exact: true })).toHaveValue('')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Full name', exact: true })).toHaveValue('Skills Example')
  await page.getByRole('button', { name: 'Edit Skills section', exact: true }).click()
  await expect(stars.getByRole('radio', { name: '4 out of 5', exact: true })).toBeChecked()
})
